spring:
  datasource:
    # 加上&rewriteBatchedStatements=true之后，批量插入的耗时从3秒多下降到109毫秒
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver